NuGetDashboard/Controllers/TrendingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Script;
using System.Web.Script.Serialization;
using NuGetDashboard.Models;
using NuGetDashboard.Utilities;
using System.Web.Helpers;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using DotNet.Highcharts;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Enums;
namespace NuGetDashboard.Controllers
{
    public class TrendingController : Controller
    {
        public ActionResult Index()       
        {
            return View();
        }

        //Returns the Net trend chart for packages 
        public ActionResult PackagesChart()
        {
            DotNet.Highcharts.Highcharts chart = GetChart("UploadsMayMonthlyReport.json", "Packages");
            return PartialView("~/Views/Home/PackagesChart.cshtml", chart);
        }

        //Returns the Net trend chart for Downloads
        public ActionResult DownloadsChart()
        {
            DotNet.Highcharts.Highcharts chart = GetChart("DownloadsMayMonthlyReport.json", "Downloads");
            return PartialView("~/Views/Home/PackagesChart.cshtml", chart);
        }

        //Returns the Net trend chart for Downloads
        public ActionResult UsersChart()
        {
            DotNet.Highcharts.Highcharts chart = GetChart("UsersMayMonthlyReport.json", "Users");
            return PartialView("~/Views/Home/PackagesChart.cshtml", chart);
        }

        private static Highcharts GetChart(string blobName, string chartName)
        {
            List<string> xValues = new List<string>();
            List<Object> yValues = new List<Object>();
            BlobStorageService.GetJsonDataFromBlob(blobName, out xValues, out yValues);

            DotNet.Highcharts.Highcharts chart = new DotNet.Highcharts.Highcharts(chartName);
            chart.SetXAxis(new XAxis
            {
                Categories = xValues.ToArray(),
            });
            chart.SetSeries(new DotNet.Highcharts.Options.Series
            {
                Data = new Data(yValues.ToArray()),
                Name = chartName
            });
            chart.SetTitle(new DotNet.Highcharts.Options.Title { Text = chartName });
            return chart;
        }


        public ActionResult ClientVersionChart()
        {
            List<string> xValues = new List<string>();
            List<Object> yValues = new List<Object>();
            BlobStorageService.GetJsonDataFromBlob("ClientVersionWeeklyReport.json", out xValues, out yValues);
            
            DotNet.Highcharts.Highcharts chart = new DotNet.Highcharts.Highcharts("DownloadsPerClient")
            .InitChart(new DotNet.Highcharts.Options.Chart { DefaultSeriesType = ChartTypes.Column })
            .SetPlotOptions(new PlotOptions
            {
                Column = new PlotOptionsColumn
                {
                    Stacking = Stackings.Normal,
                }
            });

            chart.SetXAxis(new XAxis
            {
                Categories = xValues.ToArray(),

            });
            chart.SetSeries(new DotNet.Highcharts.Options.Series
            {
                Data = new Data(yValues.ToArray()),
                Name = "DownloadsPerClient"
            });

            chart.SetTitle(new DotNet.Highcharts.Options.Title { Text = "Downloads Per Client last week" });
            return View("~/Views/Trending/PackagesChart.cshtml", chart);
        }
       

    }
}

NuGetDashboard/Views/Trending/Index.cshtml
<!-- scripts to show the Twitter Widget -->
<script src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e72e9371502bc94" type="text/javascript"></script>
<script src="http://widgets.twimg.com/j/2/widget.js"></script>  


<p style="font-family:arial;color:gray;font-size:15px;font-style:italic"> * This page shows the package upload, download and user registration trend for the current month.</p>

<div style="height:300px; width:350px; float:left; margin-right:5px">@Html.Action("DownloadsChart","Trending")
</div>
<div style="height:300px; width:350px; float:left; margin-right:5px">@Html.Action("UsersChart","Trending")
</div>
<div style="height:300px; width:350px; float:left; margin-right:5px">@Html.Action("PackagesChart","Trending")
</div>

NuGetDashboard/Views/Trending/PackagesChart.cshtml
@using DotNet.Highcharts;
@model DotNet.Highcharts.Highcharts
@Scripts.Render("http://code.highcharts.com/highcharts.js")

<p style="font-family:arial;color:gray;font-size:15px;font-style:italic"> * This page the downloads per NuGet client in the last week.</p>

@(Model)